export const mockData = [
  {
    name: "Alice",
    age: 28,
    status: "Hey, who is up for rollerblading?",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    name: "Bob",
    age: 34,
    status: "Anyone up for a game of basketball?",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    name: "Clara",
    age: 25,
    status: "Looking for a hiking buddy!",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    name: "David",
    age: 30,
    status: "Who wants to join me for a coffee?",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    name: "Eva",
    age: 22,
    status: "Let's go for a run in the park.",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    name: "Frank",
    age: 27,
    status: "Anyone up for a movie night?",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    name: "Grace",
    age: 32,
    status: "Who is in for a yoga session?",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    name: "Henry",
    age: 29,
    status: "Looking for a gym partner.",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    name: "Ivy",
    age: 26,
    status: "Let's go cycling together!",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    name: "Jack",
    age: 31,
    status: "Who wants to play some soccer?",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    name: "Karen",
    age: 24,
    status: "Anyone interested in a book club?",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    name: "Leo",
    age: 33,
    status: "Let's grab some drinks tonight!",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    name: "Mia",
    age: 21,
    status: "Looking for a shopping buddy.",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    name: "Nate",
    age: 28,
    status: "Who is up for a beach day?",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    name: "Olivia",
    age: 27,
    status: "Anyone want to go kayaking?",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    name: "Paul",
    age: 35,
    status: "Let's have a barbecue this weekend.",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    name: "Quinn",
    age: 26,
    status: "Who wants to try out the new escape room?",
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    name: "Ryan",
    age: 29,
    status: "Any gamers out there for a LAN party?",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    name: "Sophie",
    age: 24,
    status: "Looking for a buddy to explore museums.",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    name: "Tom",
    age: 30,
    status: "Anyone interested in a road trip?",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    name: "Uma",
    age: 28,
    status: "Let's hit the beach for some volleyball!",
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    name: "Victor",
    age: 27,
    status: "Who wants to join me for a music concert?",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    name: "Wendy",
    age: 25,
    status: "Looking for a partner to visit the zoo.",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    name: "Xander",
    age: 31,
    status: "Anyone up for a bike ride?",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    name: "Yara",
    age: 29,
    status: "Let's find a good spot for a picnic.",
    avatar: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    name: "Zach",
    age: 32,
    status: "Who wants to go rock climbing?",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    name: "Abby",
    age: 23,
    status: "Looking for someone to practice yoga with.",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    name: "Ben",
    age: 28,
    status: "Anyone want to join a cooking class?",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    name: "Cara",
    age: 26,
    status: "Let's check out the new art exhibit.",
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    name: "Dean",
    age: 34,
    status: "Who is up for a tennis match?",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    name: "Ella",
    age: 27,
    status: "Looking for a gardening partner.",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    name: "Fred",
    age: 30,
    status: "Anyone interested in a fishing trip?",
    avatar: "https://randomuser.me/api/portraits/men/16.jpg",
  },
];
