export const names = [
  "Alex",
  "Casey",
  "Jordan",
  "Taylor",
  "Morgan",
  "Avery",
  "Riley",
  "Cameron",
  "Jamie",
  "Quinn",
  "Dakota",
  "Skyler",
  "Parker",
  "Reese",
  "Payton",
  "Hayden",
  "Bailey",
  "Rowan",
  "Charlie",
  "Emerson",
];
export const activityStatuses = [
  "Who wants to grab a pizza?",
  "Anyone up for rollerblading?",
  "Looking for a hiking buddy!",
  "Let's go for a coffee!",
  "Who's in for a movie night?",
  "Game night, anyone?",
  "Time for some beach volleyball!",
  "Who wants to go cycling?",
  "Up for a run in the park?",
  "Picnic in the park?",
  "Let's go bowling!",
  "Anyone for a tennis match?",
  "Who's free for a BBQ?",
  "Ready for a road trip!",
  "Who wants to go fishing?",
  "Up for some rock climbing?",
  "How about a dance party?",
  "Let's hit the gym together!",
  "Looking for a shopping buddy!",
  "Who's in for a karaoke night?",
];
